name: Major Release
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  v90:
    runs-on: ubuntu-20.04
    steps:
      - name: Compile
        run: |
          sudo apt update && sudo apt install gcc g++ gfortran libglu1-mesa-dev freeglut3-dev mesa-common-dev
          wget https://www.vtk.org/files/release/9.0/VTK-9.0.1.tar.gz
          tar -xf VTK-9.0.1.tar.gz
          rm VTK-9.0.1.tar.gz
          mkdir VTK-build && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../VTK-out ../VTK-9.0.1
          sudo make install -j4
          cd ../VTK-out
          tar -cvzf ../VTK-9.0.1.tar.gz *
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: VTK-9.0.1
          path: VTK-9.0.1.tar.gz
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-9.0.1.tar.gz
          asset_name: VTK-9.0.1.tar.gz
          tag: latest
          overwrite: true
  v82:
    runs-on: ubuntu-20.04
    steps:
      - name: Compile
        run: |
          sudo apt update && sudo apt install gcc g++ gfortran libglu1-mesa-dev freeglut3-dev mesa-common-dev
          wget https://www.vtk.org/files/release/8.2/VTK-8.2.0.tar.gz
          tar -xf VTK-8.2.0.tar.gz
          rm VTK-8.2.0.tar.gz
          mkdir VTK-build && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../VTK-out ../VTK-8.2.0
          sudo make install -j4
          cd ../VTK-out
          tar -cvzf ../VTK-8.2.0.tar.gz *
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: VTK-8.2.0
          path: VTK-8.2.0.tar.gz
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-8.2.0.tar.gz
          asset_name: VTK-8.2.0.tar.gz
          tag: latest
          overwrite: true
  openblas:
    runs-on: ubuntu-20.04
    steps:
      - name: Compile
        run: |
          sudo apt update && sudo apt install gcc g++ gfortran
          wget https://github.com/xianyi/OpenBLAS/releases/download/v0.3.13/OpenBLAS-0.3.13.tar.gz
          tar -xf OpenBLAS-0.3.13.tar.gz && rm OpenBLAS-0.3.13.tar.gz && cd OpenBLAS-0.3.13
          sed -i 's/# DYNAMIC_ARCH = 1/DYNAMIC_ARCH = 1/g' Makefile.rule
          sed -i 's/# BINARY=64/BINARY=64/g' Makefile.rule
          sed -i 's/# USE_THREAD = 0/USE_THREAD = 1/g' Makefile.rule
          sed -i 's/# USE_OPENMP = 1/USE_OPENMP = 1/g' Makefile.rule
          sed -i 's/# NUM_THREADS = 24/NUM_THREADS = 20/g' Makefile.rule
          sed -i 's/# NO_SHARED = 1/NO_SHARED = 1/g' Makefile.rule
          sed -i 's/# NO_CBLAS = 1/NO_CBLAS = 1/g' Makefile.rule
          sed -i 's/# NO_LAPACKE = 1/NO_LAPACKE = 1/g' Makefile.rule
          sed -i 's/# GEMM_MULTITHREAD_THRESHOLD = 4/GEMM_MULTITHREAD_THRESHOLD = 64/g' Makefile.rule
          make
          tar -cvzf ../OpenBLAS.0.3.13.tar.gz lib*.a
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: OpenBLAS.0.3.13
          path: OpenBLAS.0.3.13.tar.gz
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenBLAS.0.3.13.tar.gz
          asset_name: OpenBLAS.0.3.13.tar.gz
          tag: latest
          overwrite: true
