name: Major Release
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  v90:
    runs-on: ubuntu-20.04
    steps:
      - name: Compile
        run: |
          echo "SP_TIME=vtk-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          sudo apt update && sudo apt install gcc g++ gfortran libglu1-mesa-dev freeglut3-dev mesa-common-dev
          wget https://www.vtk.org/files/release/9.0/VTK-9.0.1.tar.gz
          tar -xf VTK-9.0.1.tar.gz
          mkdir VTK-build && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=./VTK-out ../VTK-9.0.1
          sudo make install -j4
          tar -cvzf VTK-9.0.1.tar.gz ./VTK-out
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: VTK-9.0.1
          path: VTK-build/VTK-9.0.1.tar.gz
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-build/VTK-9.0.1.tar.gz
          asset_name: VTK-9.0.1.tar.gz
          tag: ${{ env.SP_TIME }}
          overwrite: true
  v82:
    runs-on: ubuntu-20.04
    steps:
      - name: Compile
        run: |
          echo "SP_TIME=vtk-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          sudo apt update && sudo apt install gcc g++ gfortran libglu1-mesa-dev freeglut3-dev mesa-common-dev
          wget https://www.vtk.org/files/release/8.2/VTK-8.2.0.tar.gz
          tar -xf VTK-8.2.0.tar.gz
          mkdir VTK-build && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=./VTK-out ../VTK-8.2.0
          sudo make install -j4
          tar -cvzf VTK-8.2.0.tar.gz ./VTK-out
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: VTK-8.2.0
          path: VTK-build/VTK-8.2.0.tar.gz
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-build/VTK-8.2.0.tar.gz
          asset_name: VTK-8.2.0.tar.gz
          tag: ${{ env.SP_TIME }}
          overwrite: true
