name: Major Release
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  v82-win:
    runs-on: windows-latest
    steps:
      - name: Compile
        run: |
          C:/msys64/usr/bin/wget.exe https://www.vtk.org/files/release/8.2/VTK-8.2.0.tar.gz
          tar -xf VTK-8.2.0.tar.gz
          del VTK-8.2.0.tar.gz
          mkdir VTK-build
          mkdir VTK-out
          cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=D:/a/vtk-prebuild/vtk-prebuild/VTK-out ../VTK-8.2.0
          cmake --build . --target INSTALL --config Release
          cd ../VTK-out
          7z a ../VTK-8.2.0-win.7z *
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: VTK-8.2.0-win
          path: VTK-8.2.0-win.7z
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-8.2.0-win.7z
          asset_name: VTK-8.2.0-win.7z
          tag: latest
          overwrite: true
  v82-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Compile
        run: |
          sudo apt update && sudo apt install libglu1-mesa-dev freeglut3-dev mesa-common-dev
          wget https://www.vtk.org/files/release/8.2/VTK-8.2.0.tar.gz
          tar -xf VTK-8.2.0.tar.gz && rm VTK-8.2.0.tar.gz
          mkdir VTK-build && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../VTK-out ../VTK-8.2.0
          sudo make install -j4
          cd ../VTK-out && tar -cvzf ../VTK-8.2.0-linux.tar.gz *
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: VTK-8.2.0-linux
          path: VTK-8.2.0-linux.tar.gz
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-8.2.0-linux.tar.gz
          asset_name: VTK-8.2.0-linux.tar.gz
          tag: latest
          overwrite: true
  v82-macos:
    runs-on: macos-latest
    steps:
      - name: Compile
        run: |
          sudo brew update && sudo brew install glfw3 glew
          wget https://www.vtk.org/files/release/8.2/VTK-8.2.0.tar.gz
          tar -xf VTK-8.2.0.tar.gz && rm VTK-8.2.0.tar.gz
          mkdir VTK-build && cd VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=../VTK-out ../VTK-8.2.0
          sudo make install -j4
          cd ../VTK-out && tar -cvzf ../VTK-8.2.0-macos.tar.gz *
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: VTK-8.2.0-macos
          path: VTK-8.2.0-macos.tar.gz
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VTK-8.2.0-macos.tar.gz
          asset_name: VTK-8.2.0-macos.tar.gz
          tag: latest
          overwrite: true
  openblas-win:
    runs-on: windows-latest
    steps:
      - name: Compile
        run: |
          C:/msys64/usr/bin/wget.exe https://github.com/xianyi/OpenBLAS/releases/download/v0.3.13/OpenBLAS-0.3.13.zip
          7z x OpenBLAS-0.3.13.zip
          del OpenBLAS-0.3.13.zip
          cd OpenBLAS-0.3.13
          C:/msys64/usr/bin/sed.exe -i 's/# DYNAMIC_ARCH = 1/DYNAMIC_ARCH = 1/g' Makefile.rule
          C:/msys64/usr/bin/sed.exe -i 's/# BINARY=64/BINARY=64/g' Makefile.rule
          C:/msys64/usr/bin/sed.exe -i 's/# USE_THREAD = 0/USE_THREAD = 1/g' Makefile.rule
          C:/msys64/usr/bin/sed.exe -i 's/# USE_OPENMP = 1/USE_OPENMP = 1/g' Makefile.rule
          C:/msys64/usr/bin/sed.exe -i 's/# NUM_THREADS = 24/NUM_THREADS = 20/g' Makefile.rule
          C:/msys64/usr/bin/sed.exe -i 's/# NO_CBLAS = 1/NO_CBLAS = 1/g' Makefile.rule
          C:/msys64/usr/bin/sed.exe -i 's/# NO_LAPACKE = 1/NO_LAPACKE = 1/g' Makefile.rule
          C:/msys64/usr/bin/sed.exe -i 's/# GEMM_MULTITHREAD_THRESHOLD = 4/GEMM_MULTITHREAD_THRESHOLD = 64/g' Makefile.rule
          make
          7z a ../OpenBLAS-0.3.13-win.7z libopenblas.*
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: OpenBLAS-0.3.13-win
          path: OpenBLAS-0.3.13-win.7z
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenBLAS-0.3.13-win.7z
          asset_name: OpenBLAS-0.3.13-win.7z
          tag: latest
          overwrite: true
  openblas-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Compile
        env:
          CC: gcc-9
          FC: gfortran-9
          HOSTCC: gcc-9
        run: |
          wget https://github.com/xianyi/OpenBLAS/releases/download/v0.3.13/OpenBLAS-0.3.13.tar.gz
          tar -xf OpenBLAS-0.3.13.tar.gz && rm OpenBLAS-0.3.13.tar.gz && cd OpenBLAS-0.3.13
          sed -i 's/# DYNAMIC_ARCH = 1/DYNAMIC_ARCH = 1/g' Makefile.rule
          sed -i 's/# BINARY=64/BINARY=64/g' Makefile.rule
          sed -i 's/# USE_THREAD = 0/USE_THREAD = 1/g' Makefile.rule
          sed -i 's/# USE_OPENMP = 1/USE_OPENMP = 1/g' Makefile.rule
          sed -i 's/# NUM_THREADS = 24/NUM_THREADS = 20/g' Makefile.rule
          sed -i 's/# NO_SHARED = 1/NO_SHARED = 1/g' Makefile.rule
          sed -i 's/# NO_CBLAS = 1/NO_CBLAS = 1/g' Makefile.rule
          sed -i 's/# NO_LAPACKE = 1/NO_LAPACKE = 1/g' Makefile.rule
          sed -i 's/# GEMM_MULTITHREAD_THRESHOLD = 4/GEMM_MULTITHREAD_THRESHOLD = 64/g' Makefile.rule
          make
          tar -cvzf ../OpenBLAS-0.3.13-linux.tar.gz lib*.a
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: OpenBLAS-0.3.13-linux
          path: OpenBLAS-0.3.13-linux.tar.gz
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenBLAS-0.3.13-linux.tar.gz
          asset_name: OpenBLAS-0.3.13-linux.tar.gz
          tag: latest
          overwrite: true
  openblas-macos:
    runs-on: macos-latest
    steps:
      - name: Compile
        env:
          CC: gcc-9
          FC: gfortran-9
          HOSTCC: gcc-9
          RANLIB: ranlib
        run: |
          wget https://github.com/xianyi/OpenBLAS/releases/download/v0.3.13/OpenBLAS-0.3.13.tar.gz
          tar -xf OpenBLAS-0.3.13.tar.gz && rm OpenBLAS-0.3.13.tar.gz && cd OpenBLAS-0.3.13
          sed -i '~' 's/# DYNAMIC_ARCH = 1/DYNAMIC_ARCH = 1/g' Makefile.rule
          sed -i '~' 's/# BINARY=64/BINARY=64/g' Makefile.rule
          sed -i '~' 's/# USE_THREAD = 0/USE_THREAD = 1/g' Makefile.rule
          sed -i '~' 's/# USE_OPENMP = 1/USE_OPENMP = 1/g' Makefile.rule
          sed -i '~' 's/# NUM_THREADS = 24/NUM_THREADS = 20/g' Makefile.rule
          sed -i '~' 's/# NO_SHARED = 1/NO_SHARED = 1/g' Makefile.rule
          sed -i '~' 's/# NO_CBLAS = 1/NO_CBLAS = 1/g' Makefile.rule
          sed -i '~' 's/# NO_LAPACKE = 1/NO_LAPACKE = 1/g' Makefile.rule
          sed -i '~' 's/# GEMM_MULTITHREAD_THRESHOLD = 4/GEMM_MULTITHREAD_THRESHOLD = 64/g' Makefile.rule
          make
          tar -cvzf ../OpenBLAS-0.3.13-macos.tar.gz lib*.a
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: OpenBLAS-0.3.13-macos
          path: OpenBLAS-0.3.13-macos.tar.gz
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenBLAS-0.3.13-macos.tar.gz
          asset_name: OpenBLAS-0.3.13-macos.tar.gz
          tag: latest
          overwrite: true
